version: '3.4'

services:
  fiap.pos.tech.challenge.micro.servico.producao.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
    ports:
      - "8084"
      - "8085"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro