version: '3.4'

name: fiap-pos-techchallenge-micro-servico-producao-gurpo-71

volumes:
  sql_data: {}

services:
  fiap.pos.tech.challenge.micro.servico.producao.api:
    image: fiappostechchallengemicroservicoproducaoapi:stand-alone
    depends_on:
      - mssqltools-producao
    build:
      context: ../
      dockerfile: Src/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
    ports:
      - "8084:8084"
      - "8085:8085"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  sqlserver-producao:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PSqlServer2019!", "-Q", "SELECT NAME FROM SYS.DATABASES"]
      interval: 10s
      retries: 20
    volumes:
      - sql_data:/var/opt/mssql
  mssqltools-producao:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver-producao
    volumes:
      - ./DataBase/init-database.sh:/tmp/init-database.sh
      - ../../FIAP-Pos-Tech-Challenge-Infra-Bd/Src/Modelagem-banco-de-dados/micro-servico-producao/tech-challenge-mer-1.sql:/tmp/tech-challenge-mer-1.sql
      - ../../FIAP-Pos-Tech-Challenge-Infra-Bd/Src/Modelagem-banco-de-dados/micro-servico-producao/tech-challenge-mer-2.sql:/tmp/tech-challenge-mer-2.sql
    command: /bin/bash ./tmp/init-database.sh  
